# -*- coding: utf-8 -*-
"""ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R_kp1ok01TivGNo0azLk4raKVU0vFuL_
"""

# ============================================================
# IMPORTS
# ============================================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import (mean_absolute_error, mean_squared_error,
                              r2_score, mean_absolute_percentage_error)
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# ============================================================
# LOAD PROCESSED DATA
# ============================================================
df = pd.read_csv('/content/ecommerce_processed.csv')

# ============================================================
# MODEL 1: PRICE PREDICTION (REGRESSION)
# Target: unit_price
# ============================================================
print("=" * 50)
print("MODEL 1: Price Prediction")
print("=" * 50)

FEATURES_PRICE = [
    'qty', 'freight_price', 'product_score', 'customers',
    'weekday', 'weekend', 'holiday', 'month', 'year',
    'product_weight_g', 'volume', 'product_photos_qty',
    'avg_comp_price', 'avg_comp_score', 'avg_comp_freight',
    'comp_price_ratio', 'freight_ratio', 'price_momentum',
    'category_encoded', 'product_name_lenght', 'product_description_lenght'
]

X = df[FEATURES_PRICE].fillna(0)
y = df['unit_price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

def evaluate(model, X_tr, y_tr, X_te, y_te, label):
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)
    print(f"\n{label}")
    print(f"  MAE   : {mean_absolute_error(y_te, y_pred):.4f}")
    print(f"  RMSE  : {np.sqrt(mean_squared_error(y_te, y_pred)):.4f}")
    print(f"  R²    : {r2_score(y_te, y_pred):.4f}")
    print(f"  MAPE  : {mean_absolute_percentage_error(y_te, y_pred)*100:.2f}%")
    return model, y_pred

    # Ridge
ridge, y_pred_ridge = evaluate(Ridge(alpha=1.0), X_train_sc, y_train, X_test_sc, y_test, "Ridge Regression")

# Random Forest
rf, y_pred_rf = evaluate(
    RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1),
    X_train, y_train, X_test, y_test, "Random Forest"
)

# XGBoost
xgb_model, y_pred_xgb = evaluate(
    xgb.XGBRegressor(n_estimators=300, learning_rate=0.05, max_depth=6,
                     subsample=0.8, colsample_bytree=0.8, random_state=42),
    X_train, y_train, X_test, y_test, "XGBoost"
)

# Feature Importance (XGBoost)
fi = pd.Series(xgb_model.feature_importances_, index=FEATURES_PRICE).sort_values(ascending=False)
plt.figure(figsize=(10, 6))
fi.head(15).plot(kind='barh', color='steelblue')
plt.gca().invert_yaxis()
plt.title('Top 15 Feature Importances — Price Prediction (XGBoost)')
plt.tight_layout()
plt.savefig('feature_importance_price.png', dpi=150)
plt.show()

"""**Key Insights**

1.XGBoost delivered the best performance with an R²
score of 0.992 and MAPE of 3.61%, outperforming Ridge Regression and Random Forest models.

2.Tree-based models captured pricing patterns more effectively than linear models, indicating non-linear relationships between pricing variables.

3.Freight ratio was identified as the most influential feature, highlighting the strong impact of shipping cost on e-commerce pricing strategies.

4.Competitor pricing metrics such as average competitor price and competitor price ratio significantly influenced product pricing decisions.

5.Product presentation features like description length and image count also contributed to pricing prediction performance.

6.The analysis suggests that pricing optimization requires balancing competitor positioning, logistics cost, and product attractiveness.

"""

# ============================================================
# MODEL 2: DEMAND FORECASTING (qty prediction)
# ============================================================
print("\n" + "=" * 50)
print("MODEL 2: Demand Forecasting")
print("=" * 50)

FEATURES_DEMAND = [
    'unit_price', 'freight_price', 'product_score', 'customers',
    'weekday', 'weekend', 'holiday', 'month', 'year',
    'product_weight_g', 'volume', 'avg_comp_price',
    'comp_price_ratio', 'price_momentum', 'lag_price',
    'category_encoded', 'price_x_score'
]

X_d = df[FEATURES_DEMAND].fillna(0)
y_d = df['qty']

X_d_train, X_d_test, y_d_train, y_d_test = train_test_split(
    X_d, y_d, test_size=0.2, random_state=42
)

demand_model, y_pred_demand = evaluate(
    GradientBoostingRegressor(n_estimators=300, learning_rate=0.05,
                               max_depth=5, random_state=42),
    X_d_train, y_d_train, X_d_test, y_d_test, "Gradient Boosting — Demand"
)

"""**Demand Forecasting Insights**

1.Demand prediction was significantly more complex than price prediction due to the influence of customer behavior, seasonality, and external market factors.

2.The Gradient Boosting model achieved an R² score of 0.516, indicating moderate predictive capability for product demand.

3.The model captured important demand patterns related to pricing, customer activity, and seasonal factors, but additional external variables would likely improve forecasting accuracy.

4.High MAPE values were primarily caused by low-volume products, where small prediction deviations resulted in large percentage errors.

5.The analysis demonstrates that demand forecasting in e-commerce is inherently more volatile and uncertain compared to price prediction tasks.

"""

# ============================================================
# MODEL 3: PRODUCT CLUSTERING (K-Means)
# ============================================================
print("\n" + "=" * 50)
print("MODEL 3: Product Clustering")
print("=" * 50)

CLUSTER_FEATURES = [
    'unit_price', 'avg_comp_price', 'product_score', 'qty',
    'total_price', 'freight_ratio', 'comp_price_ratio',
    'product_weight_g', 'volume', 'customers'
]

X_clust = df[CLUSTER_FEATURES].fillna(0)
scaler_c = StandardScaler()
X_clust_sc = scaler_c.fit_transform(X_clust)

# Elbow method
inertias = []
K_range = range(2, 11)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_clust_sc)
    inertias.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(K_range, inertias, 'bx-')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method — Optimal k')
plt.tight_layout()
plt.savefig('elbow_curve.png', dpi=150)
plt.show()

# Fit best k (assume 4 after elbow)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_clust_sc)

# PCA for visualisation
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_clust_sc)

plt.figure(figsize=(8, 6))
colors = ['steelblue', 'tomato', 'green', 'purple']
for c in range(4):
    idx = df['cluster'] == c
    plt.scatter(X_pca[idx, 0], X_pca[idx, 1], label=f'Cluster {c}',
                alpha=0.5, color=colors[c])
plt.legend()
plt.title('Product Clusters (PCA 2D)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.tight_layout()
plt.savefig('clusters_pca.png', dpi=150)
plt.show()

# Cluster profiles
print(df.groupby('cluster')[CLUSTER_FEATURES].mean().round(2))

"""**Product Segmentation Insights**

1.Product clustering revealed four distinct product segments based on pricing, customer demand, freight characteristics, and competitor positioning.

2.Cluster 0 represented budget-oriented products with relatively high freight burden, indicating opportunities for logistics optimization.

3.Cluster 1 contained premium products with lower demand, suggesting niche or specialized product categories.

4.Cluster 2 showed products priced significantly above competitors, potentially reflecting strong brand positioning or differentiated offerings.

5.Cluster 3 emerged as the highest-value segment, combining strong customer demand and high revenue contribution.

6.The segmentation analysis demonstrates that different product groups require different pricing and operational strategies rather than a single uniform approach.
"""

# ============================================================
# MODEL 4: COMPETITOR PRICE CLASSIFICATION
# (Will our product be overpriced / competitive / underpriced?)
# ============================================================
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

print("\n" + "=" * 50)
print("MODEL 4: Pricing Position Classifier")
print("=" * 50)

le = LabelEncoder()
df['price_position_enc'] = le.fit_transform(df['price_position'].astype(str))

FEATURES_CLASS = [
    'unit_price', 'freight_price', 'product_score', 'qty',
    'month', 'year', 'weekend', 'holiday', 'lag_price',
    'avg_comp_price', 'avg_comp_score', 'avg_comp_freight',
    'product_weight_g', 'category_encoded'
]

X_cls = df[FEATURES_CLASS].fillna(0)
y_cls = df['price_position_enc']

X_cls_tr, X_cls_te, y_cls_tr, y_cls_te = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=42, stratify=y_cls
)

clf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
clf.fit(X_cls_tr, y_cls_tr)
y_cls_pred = clf.predict(X_cls_te)

print(classification_report(y_cls_te, y_cls_pred, target_names=le.classes_))

# Confusion matrix
cm = confusion_matrix(y_cls_te, y_cls_pred)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title('Confusion Matrix — Pricing Position')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

"""**Pricing Classification Insights**

1.The pricing position classifier achieved an overall accuracy of 96%, demonstrating strong capability in identifying overpriced, competitive, and underpriced products.

2.Overpriced products showed the highest classification performance, suggesting that excessive pricing patterns are clearly distinguishable in the dataset.

3.The confusion matrix indicated minimal overlap between pricing categories, confirming strong separation between market positioning groups.

4.Competitor pricing and freight-related variables contributed significantly to classification performance.

5.The model demonstrates the potential for automated pricing monitoring systems that can support dynamic pricing and competitive strategy decisions.
"""

# ============================================================
# SAVE FINAL DATASET WITH PREDICTIONS
# ============================================================
df['predicted_price']  = xgb_model.predict(X).round(2)
df['predicted_demand'] = demand_model.predict(X_d).round(2)

print("Nulls in predicted_price :", df['predicted_price'].isna().sum())
print("Nulls in predicted_demand:", df['predicted_demand'].isna().sum())

df.to_csv('ecommerce_final.csv', index=False)
print("Final dataset saved. Shape:", df.shape)