# -*- coding: utf-8 -*-
"""Retail_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rM1HSjwEzAtshX8D4pMaPQVkjWrRTQVZ
"""

# ============================================================
# IMPORTS
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-whitegrid')

# ============================================================
# 1. LOAD DATA
# ============================================================

df = pd.read_excel('/content/retail_price.xlsx')
print(df.shape)
print(df.dtypes)
print(df.describe())

"""**Exploratory Data Analysis Insights**

1.The dataset consisted of 676 e-commerce product records with pricing, logistics, customer, and competitor-related attributes.

2.Product pricing exhibited high variability, indicating multiple pricing tiers ranging from budget to premium products.

3.Revenue distribution was heavily skewed, suggesting that a limited number of products contributed disproportionately to total sales.

4.Product ratings remained consistently high across the dataset, indicating stable customer satisfaction levels.

5.Significant variation in product weight and freight costs highlighted diverse logistics characteristics across products.

6.Competitor prices were relatively close to internal pricing, emphasizing the importance of competitive pricing strategy.

7.Sales quantity contained notable outliers, indicating the presence of high-demand products with unusually strong sales performance.

"""

# ============================================================
# 2. BASIC CLEANING
# ============================================================

#check nulls
print(df.isnull().sum())

#Check duplicates
print("Duplicates:",df.duplicated().sum())

# Convert month_year to datetime

df['month_year'] = pd.to_datetime(df['month_year'], unit='D', origin='1899-12-30')

df['month_year'] = df['month_year'].dt.strftime('%Y-%m-%d')

#Remove impossible Values

df = df[df['unit_price']>0]
df = df[df['qty']>0]

# ============================================================
# 3. OUTLIER DETECTION (IQR method)
# ============================================================

def detect_outliers_iqr(df,col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    return outliers , lower , upper

for col in ['unit_price', 'total_price', 'freight_price' , 'qty']:
  out,lo,hi = detect_outliers_iqr(df,col)
  print(f"{col}: {len(out)} outliers | range [{lo:.2f},{hi:.2f}]")

"""**Outlier Analysis Insights**

1.Outlier analysis using the IQR method identified significant variability in unit price, total revenue, freight cost, and sales quantity.

2.High unit price outliers represented premium-priced products and distinct pricing segments within the dataset.

3.Revenue outliers indicated a small number of products contributing disproportionately to total sales.

4.Freight price showed the highest number of outliers, suggesting substantial differences in logistics and shipping costs across products.

5.Quantity outliers reflected exceptionally high-demand products and potential promotional or seasonal sales spikes.

6.Outliers were retained during modeling because they reflected meaningful business patterns rather than data-quality errors.
"""

# ============================================================
# 4. UNIVARIATE ANALYSIS
# ============================================================

fig,axes = plt.subplots(2,3, figsize=(16,10))
cols = ['unit_price','total_price','freight_price','qty','product_score','customers']
for ax, col in zip(axes.flatten(),cols):
  df[col].hist(ax=ax,bins=30,color='steelblue',edgecolor='white')
  ax.set_title(col)
  ax.set_xlabel(col)
plt.tight_layout()
plt.savefig('univariate_distribution.png',dpi=150)
plt.show()

"""Most numerical variables displayed positively skewed distributions, indicating that while the majority of products operate within moderate ranges, a smaller subset of products contributes disproportionately to revenue, customer engagement, and sales volume."""

# ============================================================
# 5. CORRELATION HEATMAP
# ============================================================

nums_cols = df.select_dtypes(include=np.number).columns.tolist()
corr = df[nums_cols].corr()

plt.figure(figsize=(16,14))
mask = np.triu(np.ones_like(corr,dtype=bool))
sns.heatmap(
       corr,mask = mask,annot=True,fmt='.2f',
       cmap='coolwarm', center = 0,
       linewidths=0.5,annot_kws={'size':8}
)
plt.title('Feature Correlation Heatmap',fontsize =14)
plt.tight_layout()
plt.savefig('correlation_heatmap.png',dpi=150)
plt.show()

# ============================================================
# 6. BIVARIATE ANALYSIS
# ============================================================

# Unit price vs Total price
plt.figure(figsize=(8,5))
plt.scatter(df['unit_price'],df['total_price'],alpha=0.4,color='teal')
plt.xlabel('Unit Price')
plt.ylabel('Total Price')
plt.title('Unit price vs Total price')
plt.tight_layout()
plt.savefig('price_scatter.png',dpi=150)
plt.show()

#Category revenue Boxplot
plt.figure(figsize=(14,6))
top_cats = df.groupby('product_category_name')['total_price'].sum().nlargest(10).index
df[df['product_category_name'].isin(top_cats)].boxplot(
    column='unit_price',by='product_category_name',figsize=(14,6)
)
plt.xticks(rotation=45,ha='right')
plt.title('Unit price by Category(top 10)')
plt.suptitle('')
plt.tight_layout()
plt.savefig('category_price_box.png',dpi=150)
plt.show()

# ============================================================
# 7. TIME SERIES — MONTHLY REVENUE
# ============================================================

monthly = df.groupby('month_year').agg(
    total_revenue=('total_price', 'sum'),
    total_qty=('qty', 'sum'),
    avg_price=('unit_price', 'mean')
).reset_index().sort_values('month_year')

fig, ax1 = plt.subplots(figsize=(14, 5))
ax2 = ax1.twinx()
ax1.plot(monthly['month_year'], monthly['total_revenue'], color='steelblue', label='Revenue', lw=2)
ax2.bar(monthly['month_year'], monthly['total_qty'], alpha=0.3, color='orange', label='Qty')
ax1.set_ylabel('Revenue')
ax2.set_ylabel('Quantity')
ax1.set_title('Monthly Revenue & Quantity Trend')
plt.tight_layout()
plt.savefig('monthly_trend.png', dpi=150)
plt.show()

# ============================================================
# 8. COMPETITOR PRICE ANALYSIS
# ============================================================
df['avg_comp_price'] = (df['comp_1'] + df['comp_2'] + df['comp_3']) / 3
df['price_vs_comp']  = df['unit_price'] - df['avg_comp_price']
df['price_position'] = pd.cut(
    df['price_vs_comp'],
    bins=[-np.inf, -1, 1, np.inf],
    labels=['Underpriced', 'Competitive', 'Overpriced']
)
print(df['price_position'].value_counts())

plt.figure(figsize=(8, 5))
df['price_position'].value_counts().plot(kind='bar', color=['green', 'gray', 'red'])
plt.title('Product Pricing Position vs Competitors')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('pricing_position.png', dpi=150)
plt.show()

# ============================================================
# 9. PRICE ELASTICITY ANALYSIS
# ============================================================
df_elast = df[df['lag_price'] > 0].copy()
df_elast['price_change_pct'] = (df_elast['unit_price'] - df_elast['lag_price']) / df_elast['lag_price']
df_elast['qty_change'] = df_elast.groupby('product_id')['qty'].pct_change()
df_elast.dropna(subset=['qty_change'], inplace=True)

df_elast['elasticity'] = df_elast['qty_change'] / df_elast['price_change_pct'].replace(0, np.nan)
df_elast['elasticity'].clip(-10, 10, inplace=True)

print("Average Price Elasticity:", df_elast['elasticity'].mean())
print(df_elast.groupby('product_category_name')['elasticity'].mean().sort_values())

# ============================================================
# 10. FEATURE ENGINEERING
# ============================================================
# Competitor relative metrics
df['comp_price_ratio']  = df['unit_price'] / df['avg_comp_price'].replace(0, np.nan)
df['freight_ratio']     = df['freight_price'] / df['unit_price'].replace(0, np.nan)
df['revenue_per_unit']  = df['total_price'] / df['qty'].replace(0, np.nan)
df['price_momentum']    = df['unit_price'] - df['lag_price']

# Avg competitor score and freight
df['avg_comp_score']    = (df['ps1'] + df['ps2'] + df['ps3']) / 3
df['avg_comp_freight']  = (df['fp1'] + df['fp2'] + df['fp3']) / 3

# Category encoding
df['category_encoded'] = df['product_category_name'].astype('category').cat.codes

# Interaction features
df['price_x_score']    = df['unit_price'] * df['product_score']
df['weight_volume']    = df['product_weight_g'] * df['volume']

print("New features added. Shape:", df.shape)
df.to_csv('ecommerce_processed.csv', index=False)